services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
      - NODE_ENV=production
    volumes:
      - .:/app