
# docker/Dockerfile.prod
FROM node:20

# Ishlash uchun kerakli muhitni o'rnatish
WORKDIR /app

# Kerakli fayllarni ko'chirish
COPY package*.json ./
RUN npm install --production

# Loyiha fayllarini ko'chirish
COPY . .

# Loyiha build jarayoni
RUN npm run build

# Ishga tushirish komandasi
CMD ["node", "dist/main"]
